import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler,projectId} from '../src/cloud-api.js';
import {applyProjectAction,createProject} from '../src/domain.js';
const candidate={provider:'manual',externalId:'manual-1',title:'Test',originalUrl:'https://example.com',sourceName:'Manual'};
const plan={title:'Title',angle:'Angle',outline:'Outline'};
const evidence={sources:['https://example.com'],notes:'Evidence',confirmed:true};
function setup(){
 const records=new Map();let identity={uid:'owner-a',isAnonymous:false};
 const db={collection(name){assert.equal(name,'projects');return {doc(id){return {id,async get(){const p=records.get(id);return {data:p?[structuredClone(p)]:[]};}};},where(filter){let offset=0,limit=100;return {skip(v){offset=v;return this;},limit(v){limit=v;return this;},async get(){return {data:[...records.values()].filter(x=>x.ownerId===filter.ownerId).slice(offset,offset+limit).map(x=>structuredClone(x))};}};} };},async startTransaction(){let write,readRevision,readId;return {async get(ref){readId=ref.id;const old=records.get(ref.id);readRevision=old?.revision;return {data:()=>old?structuredClone(old):null};},async set(ref,data){assert.ok(!Object.hasOwn(data,'_id'),'SDK forbids _id in set payload');write={id:ref.id,data:structuredClone(data)};},async commit(){if(records.get(readId)?.revision!==readRevision)throw Object.assign(new Error('write conflict'),{code:'DATABASE_TRANSACTION_CONFLICT'});if(write)records.set(write.id,{...write.data,_id:write.id});},async rollback(){}};}};
 const handler=makeHandler({db,getIdentity:async()=>identity,allowedUids:['owner-a','owner-b'],loadFeed:async window=>({window,items:[]})});
 return {handler,records,setIdentity:v=>identity=v};
}
test('reject missing or anonymous identity, ignore caller supplied UID',async()=>{const f=setup();f.setIdentity({uid:'',isAnonymous:false});assert.equal((await f.handler({action:'projects.list',uid:'owner-a'})).error.code,'UNAUTHENTICATED');f.setIdentity({uid:'owner-a',isAnonymous:true});assert.equal((await f.handler({action:'feed'})).error.code,'UNAUTHENTICATED');});
test('allowlist is required for data operations while whoami supports deployment setup',async()=>{const f=setup();f.setIdentity({uid:'stranger',isAnonymous:false});assert.deepEqual((await f.handler({action:'whoami'})).data,{uid:'stranger',authorized:false});assert.equal((await f.handler({action:'projects.list'})).error.code,'FORBIDDEN');});
test('duplicate selection returns one project and IDs are scoped to owner',async()=>{const f=setup();const a=await f.handler({action:'projects.create',candidate});const b=await f.handler({action:'projects.create',candidate});assert.equal(a.data.id,b.data.id);assert.equal(f.records.size,1);assert.notEqual(projectId('owner-a',candidate),projectId('owner-b',candidate));assert.equal(a.data.ownerId,undefined);});
test('owner isolation applies to list and mutation',async()=>{const f=setup();const p=(await f.handler({action:'projects.create',candidate})).data;f.setIdentity({uid:'owner-b',isAnonymous:false});assert.equal((await f.handler({action:'projects.list'})).data.items.length,0);assert.equal((await f.handler({action:'projects.mutate',id:p.id,expectedRevision:0,command:'save_plan',payload:{plan,evidence},ownerId:'owner-a'})).error.code,'NOT_FOUND');});
test('approval, render, stale invalidation are enforced on server; client HTML is ignored',async()=>{const f=setup();let p=(await f.handler({action:'projects.create',candidate})).data;const mutate=async(command,payload)=>f.handler({action:'projects.mutate',id:p.id,expectedRevision:p.revision,command,payload});assert.equal((await mutate('render',{markdown:'Body',audited:true})).error.code,'INVALID_STATE');p=(await mutate('approve_plan',{plan,evidence})).data;assert.equal(p.revision,1);p=(await mutate('render',{markdown:'<script>alert(1)</script>',audited:true,html:'<script>bad</script>'})).data;assert.equal(p.stage,'preview_ready');assert.ok(!p.output.html.includes('<script>'));p=(await mutate('save_plan',{plan:{...plan,angle:'Changed'},evidence})).data;assert.equal(p.stale.render,true);assert.equal(p.stale.draft,true);});
test('stale revisions cannot overwrite data',async()=>{const f=setup();const p=(await f.handler({action:'projects.create',candidate})).data;const event={action:'projects.mutate',id:p.id,expectedRevision:0,command:'save_plan',payload:{plan,evidence}};assert.equal((await f.handler(event)).ok,true);assert.equal((await f.handler(event)).error.code,'CONFLICT');assert.equal(f.records.get(p.id).revision,1);});
test('candidate URLs and excessive payloads are rejected before writes',async()=>{const f=setup();assert.equal((await f.handler({action:'projects.create',candidate:{...candidate,originalUrl:'javascript:alert(1)'}})).error.code,'INVALID_INPUT');assert.equal((await f.handler({action:'projects.create',candidate:{...candidate,title:'x'.repeat(501)}})).error.code,'INVALID_INPUT');assert.equal(f.records.size,0);});
test('render requires explicit review and all transitions increment revisions',()=>{let p=createProject(candidate);p=applyProjectAction(p,'approve_plan',{plan,evidence});assert.equal(p.revision,1);assert.throws(()=>applyProjectAction(p,'render',{markdown:'Body',audited:false}));p=applyProjectAction(p,'render',{markdown:'Body',audited:true});assert.equal(p.revision,2);});
test('project lists contain lightweight summaries and full reads enforce ownership',async()=>{const f=setup();const p=(await f.handler({action:'projects.create',candidate})).data;const list=(await f.handler({action:'projects.list'})).data.items;assert.equal(list[0].partial,true);assert.equal(list[0].draft,undefined);assert.equal((await f.handler({action:'projects.get',id:p.id})).data.candidate.title,candidate.title);f.setIdentity({uid:'owner-b',isAnonymous:false});assert.equal((await f.handler({action:'projects.get',id:p.id})).error.code,'NOT_FOUND');});
