import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {build} from 'esbuild';
import {resolve} from 'node:path';
import {createProject,applyProjectAction} from '../src/domain.js';
async function mount(mode='local',api){
 const w=new Window({url:'http://localhost:3000',settings:{disableCSSFileLoading:true,disableComputedStyleRendering:true}});
 w.document.body.innerHTML='<div id="app"></div>';w.structuredClone=structuredClone;w.__api=api;
 const out=await build({entryPoints:['public/app.js'],bundle:true,write:false,format:'esm',platform:'browser',plugins:[{name:'test-adapters',setup(b){b.onResolve({filter:/^\/domain\.js$/},()=>({path:resolve('src/domain.js')}));b.onResolve({filter:/config\.js$/},()=>({path:'config',namespace:'fake'}));b.onResolve({filter:/cloud-client\.js$/},()=>({path:'cloud',namespace:'fake'}));b.onLoad({filter:/.*/,namespace:'fake'},args=>({contents:args.path==='config'?`export const config={mode:'${mode}'};`:'export const session=()=>window.__api.session(); export const login=(...args)=>window.__api.login(...args); export const logout=()=>window.__api.logout(); export const call=(...args)=>window.__api.call(...args);',loader:'js'}));}}]});
 await w.eval(`(async()=>{${out.outputFiles[0].text}\n})()`);
 return w;
}
const tick=()=>new Promise(r=>setTimeout(r,15));
async function click(w,id){const el=w.document.getElementById(id);assert.ok(el,'missing '+id);el.click();await tick();}
function fill(w,id,value){const el=w.document.getElementById(id);assert.ok(el,'missing '+id);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
function checkbox(w,id){w.document.getElementById(id).checked=true;}
async function plan(w){fill(w,'sources','https://example.com');fill(w,'notes','事实摘录');checkbox(w,'verified');fill(w,'angle','用户影响');fill(w,'outline','一、事实\n二、影响');await click(w,'approve');}
test('DOM flow: manual selection, planning, preview, copy and upstream invalidation',async()=>{const w=await mount();try{fill(w,'manual-title','手动测试');await click(w,'manual');assert.ok(w.location.hash.includes('/desk/'));await plan(w);assert.ok(w.location.hash.includes('/studio/'));fill(w,'draft','## 标题\n\n正文<script>');checkbox(w,'audit');await click(w,'preview');assert.ok(w.document.querySelector('.paper'));assert.equal(w.document.getElementById('copy').disabled,false);assert.ok(!w.document.querySelector('.paper script'));fill(w,'draft','修改正文');assert.equal(w.document.getElementById('audit').checked,false);assert.equal(w.document.getElementById('copy').disabled,true);await click(w,'back');fill(w,'angle','新角度');await click(w,'save-plan');await click(w,'nav-studio');assert.equal(w.document.getElementById('copy').disabled,true);assert.equal(w.document.getElementById('preview').disabled,true);const stored=JSON.parse(w.localStorage.getItem('writter.projects.v1'));assert.equal(stored[0].stale.render,true);}finally{await w.happyDOM.close();}});
test('cloud DOM path: saves through commands, stays on form after a revision conflict',async()=>{let project;let fail=false;const calls=[];const api={session:async()=>({}),call:async(action,data)=>{calls.push(action);if(action==='whoami')return {uid:'owner',authorized:true};if(action==='projects.list')return {items:project?[project]:[],nextOffset:null};if(action==='projects.create'){project=createProject(data.candidate,'a'.repeat(64));return project;}if(action==='projects.mutate'){if(fail)throw Object.assign(new Error('版本冲突'),{code:'CONFLICT'});project=applyProjectAction(project,data.command,data.payload);return project;}throw Error(action);}};const w=await mount('cloud',api);try{fill(w,'manual-title','Cloud project');await click(w,'manual');await plan(w);fill(w,'draft','云端正文');checkbox(w,'audit');await click(w,'preview');assert.equal(project.stage,'preview_ready');assert.equal(w.localStorage.getItem('writter.projects.v1'),null);await click(w,'back');fill(w,'angle','未保存输入');fail=true;await click(w,'save-plan');assert.equal(w.document.getElementById('angle').value,'未保存输入');assert.match(w.document.querySelector('.toast').textContent,/版本冲突/);assert.ok(calls.includes('projects.mutate'));}finally{await w.happyDOM.close();}});
test('cloud login gate requires a session and captures submit without page navigation',async()=>{let logged=false;const api={session:async()=>null,login:async(user,password)=>{assert.equal(user,'asteria');assert.equal(password,'test-password');logged=true;return {};},call:async action=>action==='whoami'?{uid:'owner',authorized:true}:{items:[],nextOffset:null}};const w=await mount('cloud',api);try{assert.ok(w.document.getElementById('login-form'));fill(w,'username','asteria');fill(w,'password','test-password');const ev=new w.Event('submit',{bubbles:true,cancelable:true});w.document.getElementById('login-form').dispatchEvent(ev);await tick();assert.equal(ev.defaultPrevented,true);assert.equal(logged,true);assert.ok(w.document.getElementById('manual-title'));}finally{await w.happyDOM.close();}});
test('installed browser SDK exposes the authentication and function APIs actually used',async()=>{const out=await build({entryPoints:['src/cloud-sdk.js'],bundle:true,write:false,format:'iife',globalName:'WritterSDK',platform:'browser'});const w=new Window({url:'http://localhost:3000'});try{w.eval(out.outputFiles[0].text);const app=w.eval("WritterSDK.default.init({env:'writter-dev-d0g7h1prq4ce60665',region:'ap-shanghai'})");assert.equal(typeof app.auth.getSession,'function');assert.equal(typeof app.auth.signInWithPassword,'function');assert.equal(typeof app.callFunction,'function');}finally{await w.happyDOM.close();}});
